spring:
  application:
    name: ecommerce-system
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:ecommerce_db}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:update}
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: ${FORMAT_SQL:false}
        dialect: org.hibernate.dialect.MySQL8Dialect
        globally_quoted_identifiers: true
        jdbc:
          time_zone: UTC
  security:
    jwt:
      secret: ${JWT_SECRET:}
      expiration: ${JWT_EXPIRATION:86400000} # 24 horas em milliseconds

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    com.ecommerce: ${LOG_LEVEL:INFO}
    org.hibernate.SQL: ${HIBERNATE_SQL_LOG:false}
    org.hibernate.type.descriptor.sql.BasicBinder: ${HIBERNATE_BINDER_LOG:false}
